[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@account-abstraction/=node_modules/@account-abstraction/contracts/",
    "forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL:-https://sepolia.base.org}"

# [etherscan]
# base_sepolia = { key = "${BASESCAN_API_KEY}" }
# Uncomment above and set BASESCAN_API_KEY if you want to verify contracts

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
